
name: Python CI Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Python File
        run: python test.py

      - name: Verify Output
        run: |
          python -c "assert 10 + 20 == 30"
